### ISSUE TITLE
UI for My Pantry page

### ISSUE THREAD

**Issue by reddpy** [PantryChef/PantryChef#21] opened 2017-08-31 03:57 UTC
Create a UI for the My Pantry page. 
V0 includes a button to add ingredients and list view box that would populate a list of ingredients in your pantry. 

clicking the button would bring a custom dialogue alert input that would prompt for the name of the item, the quantity and unit of measurement (separate issue). This issue of creating the V0 UI is already complete.

**Comment by brandonschabell** [comment] 2017-08-31 04:05
@KJ-Caramel This looks like a duplicate of part of issue #7.

**Comment by reddpy** [comment] 2017-08-31 04:06
@brandonschabell I did this so that I could merge this in and one of us could take sub-tasks if we wanted to

**Closed as completed** 2017-08-31 04:13 UTC
